// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentStatus } from "./AgentStatus";

/**
 * Full agent metadata stored in the registry.
 */
export type AgentRegistration = { 
/**
 * Unique agent identifier.
 */
agent_id: AgentId, 
/**
 * Human-readable agent name (must be non-empty).
 */
name: string, 
/**
 * The agent's home namespace URI.
 */
namespace: string, 
/**
 * Capabilities this agent advertises (e.g., "code_review", "testing").
 */
capabilities: Array<string>, 
/**
 * Parent agent if this was spawned.
 */
parent_agent: AgentId | null, 
/**
 * When this agent was registered.
 */
registered_at: string, 
/**
 * Last heartbeat timestamp.
 */
last_active: string, 
/**
 * Current lifecycle status.
 */
status: AgentStatus, };
