// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TrustEvidence } from "./TrustEvidence";

/**
 * Trust relationship from one agent toward another.
 */
export type AgentTrust = { 
/**
 * The agent holding this trust assessment.
 */
agent_id: AgentId, 
/**
 * The agent being assessed.
 */
target_agent: AgentId, 
/**
 * Overall trust score in [0.0, 1.0].
 */
overall_trust: number, 
/**
 * Per-domain trust scores (domain name → score in [0.0, 1.0]).
 */
domain_trust: { [key in string]: number }, 
/**
 * Evidence supporting this trust assessment.
 */
evidence: TrustEvidence, 
/**
 * When this trust was last updated.
 */
last_updated: string, };
