// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * UUID-based agent identifier.
 *
 * Wraps a `String` for type safety. Use [`AgentId::new()`] for a fresh UUID
 * or [`AgentId::default_agent()`] for the backward-compatible sentinel value.
 */
export type AgentId = string;
