// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Confidence } from "./Confidence";
import type { ConstraintLink } from "./ConstraintLink";
import type { FileLink } from "./FileLink";
import type { FunctionLink } from "./FunctionLink";
import type { Importance } from "./Importance";
import type { MemoryType } from "./MemoryType";
import type { NamespaceId } from "./NamespaceId";
import type { PatternLink } from "./PatternLink";
import type { TypedContent } from "./TypedContent";

/**
 * The universal memory struct. Every memory in the system is a BaseMemory.
 */
export type BaseMemory = { 
/**
 * UUID v4 identifier.
 */
id: string, 
/**
 * The type of this memory.
 */
memory_type: MemoryType, 
/**
 * Typed content — per-type struct, NOT a JSON blob.
 */
content: TypedContent, 
/**
 * ~20 token summary for Level 1 compression.
 */
summary: string, 
/**
 * When we learned this (bitemporal: transaction time).
 */
transaction_time: string, 
/**
 * When this was/is true (bitemporal: valid time).
 */
valid_time: string, 
/**
 * Optional expiry.
 */
valid_until: string | null, 
/**
 * Confidence score, decays over time.
 */
confidence: Confidence, 
/**
 * Importance level.
 */
importance: Importance, 
/**
 * Last time this memory was accessed.
 */
last_accessed: string, 
/**
 * Number of times accessed.
 */
access_count: bigint, 
/**
 * Linked code patterns.
 */
linked_patterns: Array<PatternLink>, 
/**
 * Linked constraints.
 */
linked_constraints: Array<ConstraintLink>, 
/**
 * Linked files with citation info.
 */
linked_files: Array<FileLink>, 
/**
 * Linked functions.
 */
linked_functions: Array<FunctionLink>, 
/**
 * Free-form tags.
 */
tags: Array<string>, 
/**
 * Whether this memory has been archived.
 */
archived: boolean, 
/**
 * ID of the memory that supersedes this one.
 */
superseded_by: string | null, 
/**
 * ID of the memory this one supersedes.
 */
supersedes: string | null, 
/**
 * blake3 hash of content for dedup and embedding cache.
 */
content_hash: string, 
/**
 * Namespace this memory belongs to. Default: agent://default/.
 */
namespace: NamespaceId, 
/**
 * Agent that created this memory. Default: AgentId::default_agent().
 */
source_agent: AgentId, };
