// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Anti-patterns with bad/good examples. Half-life: 90d
 */
export type CodeSmellContent = { smell_name: string, description: string, bad_example: string, good_example: string, severity: string, };
