// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence score clamped to [0.0, 1.0].
 * Represents how confident the system is in a memory's accuracy.
 */
export type Confidence = number;
