// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approved exceptions to constraints. Half-life: 90d
 */
export type ConstraintOverrideContent = { constraint_name: string, override_reason: string, approved_by: string, scope: string, expiry: string | null, };
