// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a cross-agent contradiction is resolved.
 */
export type ContradictionResolution = { "strategy": "trust_wins" } | { "strategy": "needs_human_review" } | { "strategy": "context_dependent" } | { "strategy": "temporal_supersession" };
