// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summarized past discussions. Half-life: 30d
 */
export type ConversationContent = { summary: string, participants: Array<string>, key_points: Array<string>, };
