// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relationship types between memories owned by different agents.
 */
export type CrossAgentRelation = { "type": "informed_by" } | { "type": "decision_based_on" } | { "type": "independent_corroboration" } | { "type": "cross_agent_contradiction" } | { "type": "refinement" };
