// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ContradictionResolution } from "./ContradictionResolution";

/**
 * A detected contradiction between two agents' memories.
 */
export type CrossAgentContradiction = { 
/**
 * First memory in the contradiction.
 */
memory_a: string, 
/**
 * Agent that owns memory_a.
 */
agent_a: AgentId, 
/**
 * Trust score of agent_a.
 */
trust_a: number, 
/**
 * Second memory in the contradiction.
 */
memory_b: string, 
/**
 * Agent that owns memory_b.
 */
agent_b: AgentId, 
/**
 * Trust score of agent_b.
 */
trust_b: number, 
/**
 * Type of contradiction.
 */
contradiction_type: string, 
/**
 * How this contradiction was or should be resolved.
 */
resolution: ContradictionResolution, };
