// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Code decision context linked to ADRs. Half-life: 180d
 */
export type DecisionContextContent = { decision: string, context: string, adr_link: string | null, trade_offs: Array<string>, };
