// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * System/environment configurations. Half-life: 90d
 */
export type EnvironmentContent = { name: string, config: JsonValue, platform: string | null, };
