// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw interaction records. Half-life: 7d
 */
export type EpisodicContent = { interaction: string, context: string, outcome: string | null, };
