// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Corrections and learning signals. Half-life: 120d
 */
export type FeedbackContent = { feedback: string, category: string, source: string, };
