// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BudgetAllocation } from "./BudgetAllocation";

/**
 * Context assembled for LLM generation with budget allocation and provenance.
 */
export type GenerationContext = { 
/**
 * Memories organized by allocation category.
 */
allocations: Array<BudgetAllocation>, 
/**
 * Total tokens used.
 */
total_tokens: number, 
/**
 * Total budget available.
 */
total_budget: number, };
