// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Objectives with progress tracking. Half-life: 90d
 */
export type GoalContent = { title: string, description: string, progress: number, milestones: Array<string>, };
