// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealingActionType } from "./HealingActionType";

/**
 * An automatic healing action.
 */
export type HealingAction = { action_type: HealingActionType, description: string, applied: boolean, };
