// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory importance level. Affects decay rate, compression priority, and retrieval ranking.
 */
export type Importance = "low" | "normal" | "high" | "critical";
