// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Postmortems with root cause. Half-life: 365d
 */
export type IncidentContent = { title: string, root_cause: string, impact: string, resolution: string, lessons_learned: Array<string>, };
