// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of analyzing a correction.
 */
export type LearningResult = { 
/**
 * Category of the correction (e.g., "factual", "procedural", "preference").
 */
category: string, 
/**
 * Extracted principle, if any.
 */
principle: string | null, 
/**
 * ID of the memory created from this learning, if any.
 */
memory_created: string | null, };
