// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * The scope of a namespace, determining visibility and default permissions.
 */
export type NamespaceScope = { "type": "agent", "value": AgentId } | { "type": "team", "value": string } | { "type": "project", "value": string };
