// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission levels for namespace access.
 */
export type NamespacePermission = "read" | "write" | "share" | "admin";
