// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why patterns exist, with business context. Half-life: 180d
 */
export type PatternRationaleContent = { pattern_name: string, rationale: string, business_context: string, examples: Array<string>, };
