// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of predictive preloading.
 */
export type PredictionResult = { 
/**
 * IDs of predicted memories.
 */
memory_ids: Array<string>, 
/**
 * Signals that triggered the prediction.
 */
signals: Array<string>, 
/**
 * Overall prediction confidence.
 */
confidence: number, };
