// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * User/team preferences. Half-life: 120d
 */
export type PreferenceContent = { preference: string, scope: string, value: JsonValue, };
