// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Importance } from "./Importance";
import type { MemoryType } from "./MemoryType";

/**
 * Filter criteria for memory projections.
 */
export type ProjectionFilter = { 
/**
 * Only include these memory types (empty = all).
 */
memory_types: Array<MemoryType>, 
/**
 * Minimum confidence threshold.
 */
min_confidence: number | null, 
/**
 * Minimum importance level.
 */
min_importance: Importance | null, 
/**
 * Only include memories linked to these files.
 */
linked_files: Array<string>, 
/**
 * Only include memories with these tags.
 */
tags: Array<string>, 
/**
 * Maximum age in days.
 */
max_age_days: bigint | null, 
/**
 * Custom predicate expression (future use).
 */
predicate: string | null, };
