// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a memory was originally created.
 */
export type ProvenanceOrigin = { "type": "human" } | { "type": "agent_created" } | { "type": "derived" } | { "type": "imported" } | { "type": "projected" };
