// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Actions that can appear in a provenance chain.
 */
export type ProvenanceAction = "created" | "shared_to" | "projected_to" | "merged_with" | "consolidated_from" | "validated_by" | "used_in_decision" | "corrected_by" | "reclassified_from" | "retracted";
