// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * External references/citations. Half-life: 60d
 */
export type ReferenceContent = { title: string, url: string | null, citation: string, };
