// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 14 relationship types between memories.
 */
export type RelationshipType = "supersedes" | "supports" | "contradicts" | "related" | "derived_from" | "owns" | "affects" | "blocks" | "requires" | "references" | "learned_from" | "assigned_to" | "depends_on" | "cross_agent";
