// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intent } from "./Intent";

/**
 * Context for a retrieval request.
 */
export type RetrievalContext = { 
/**
 * The user's query or focus area.
 */
focus: string, 
/**
 * Detected intent.
 */
intent: Intent | null, 
/**
 * Active files in the editor.
 */
active_files: Array<string>, 
/**
 * Token budget for the response.
 */
budget: number, 
/**
 * Memory IDs already sent in this session (for dedup).
 */
sent_ids: Array<string>, };
