// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session state for deduplication and token tracking.
 */
export type SessionContext = { session_id: string, 
/**
 * Memory IDs already sent in this session.
 */
sent_memory_ids: Array<string>, 
/**
 * Total tokens used in this session.
 */
tokens_used: number, 
/**
 * Token budget for this session.
 */
token_budget: number, };
