// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Knowledge domains and proficiency. Half-life: 180d
 */
export type SkillContent = { skill_name: string, proficiency: string, domain: string, evidence: Array<string>, };
