// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Configuration for spawning a sub-agent.
 */
export type SpawnConfig = { 
/**
 * The parent agent spawning this sub-agent.
 */
parent_agent: AgentId, 
/**
 * Optional projection from parent namespace to give the sub-agent context.
 */
projection: string | null, 
/**
 * Trust discount factor applied to inherited trust scores (default: 0.8).
 */
trust_discount: number, 
/**
 * Whether to auto-promote sub-agent memories to parent namespace on deregister.
 */
auto_promote_on_deregister: boolean, 
/**
 * Optional time-to-live in seconds.
 */
ttl: bigint | null, };
