// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Institutional knowledge. Half-life: 365d
 */
export type TribalContent = { knowledge: string, severity: string, warnings: Array<string>, consequences: Array<string>, };
