// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhyEntry } from "./WhyEntry";

/**
 * Context for answering "why is it this way?" questions.
 */
export type WhyContext = { patterns: Array<WhyEntry>, decisions: Array<WhyEntry>, tribal: Array<WhyEntry>, warnings: Array<string>, };
