import type { StylingDNAProfile, Gene } from './types.js';

export class PlaybookGenerator {
  generate(profile: StylingDNAProfile): string {
    const lines: string[] = [
      '# Styling Playbook',
      `> Auto-generated by drift DNA analysis. Last updated: ${profile.summary.lastUpdated}`,
      '',
      '## Quick Reference',
      '',
      '| Concern | Our Approach | Confidence |',
      '|---------|--------------|------------|',
    ];

    for (const gene of Object.values(profile.genes)) {
      const approach = gene.dominant?.name ?? 'Not established';
      const conf = `${Math.round(gene.confidence * 100)}%`;
      lines.push(`| ${gene.name} | ${approach} | ${conf} |`);
    }

    lines.push('', `## Health Score: ${profile.summary.healthScore}/100`, '');

    for (const gene of Object.values(profile.genes)) {
      lines.push(...this.generateGeneSection(gene));
    }

    if (profile.mutations.length > 0) {
      lines.push('---', '', '## Mutations', '', 'Files deviating from established patterns:', '');
      for (const m of profile.mutations.slice(0, 10)) {
        lines.push(`- **${m.file}:${m.line}** - ${m.actual} (expected: ${m.expected})`);
      }
      if (profile.mutations.length > 10) {lines.push(`- ... and ${profile.mutations.length - 10} more`);}
    }

    return lines.join('\n');
  }

  private generateGeneSection(gene: Gene): string[] {
    const lines: string[] = ['---', '', `## ${gene.name}`, ''];
    if (gene.dominant) {
      lines.push(`**Our Pattern**: ${gene.dominant.name}`, '', gene.dominant.description, '');
      if (gene.dominant.examples.length > 0) {
        const ex = gene.dominant.examples[0];
        if (ex) {lines.push('```tsx', ex.code, '```', '');}
      }
      lines.push('**Exemplar Files**:', '');
      for (const f of gene.exemplars.slice(0, 3)) {lines.push(`- \`${f}\``);}
      const avoid = gene.alleles.filter(a => !a.isDominant).map(a => a.name);
      if (avoid.length > 0) {lines.push('', '**Avoid**:', '', ...avoid.map(a => `- ${a}`));}
    } else {
      lines.push('*No dominant pattern established*', '');
    }
    return lines;
  }
}
