// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Reusable agent configurations. Half-life: 365d
 */
export type AgentSpawnContent = { agent_name: string, configuration: JsonValue, purpose: string, };
