// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressedMemory } from "./CompressedMemory";

export type BudgetAllocation = { category: string, 
/**
 * Percentage of budget allocated to this category.
 */
percentage: number, memories: Array<CompressedMemory>, tokens_used: number, };
