// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NarrativeSection } from "./NarrativeSection";

/**
 * A generated narrative explaining causal relationships.
 */
export type CausalNarrative = { sections: Array<NarrativeSection>, summary: string, confidence: number, };
