// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Importance } from "./Importance";
import type { MemoryType } from "./MemoryType";

/**
 * A memory compressed to one of 4 levels for token-efficient context injection.
 */
export type CompressedMemory = { memory_id: string, memory_type: MemoryType, importance: Importance, 
/**
 * Compression level: 0 (IDs only) through 3 (full context).
 */
level: number, 
/**
 * The compressed text representation.
 */
text: string, 
/**
 * Actual token count of the compressed text.
 */
token_count: number, 
/**
 * Relevance score from retrieval ranking.
 */
relevance_score: number, };
