// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality metrics for a consolidation operation.
 */
export type ConsolidationMetrics = { 
/**
 * Precision of the consolidation (0.0–1.0).
 */
precision: number, 
/**
 * Compression ratio achieved.
 */
compression_ratio: number, 
/**
 * Information lift from consolidation.
 */
lift: number, 
/**
 * Stability of the consolidated memory.
 */
stability: number, };
