// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsolidationMetrics } from "./ConsolidationMetrics";

/**
 * Result of a consolidation operation.
 */
export type ConsolidationResult = { 
/**
 * IDs of newly created consolidated memories.
 */
created: Array<string>, 
/**
 * IDs of memories archived after consolidation.
 */
archived: Array<string>, 
/**
 * Quality metrics for this consolidation.
 */
metrics: ConsolidationMetrics, };
