// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Core project/workspace metadata. Half-life: ∞
 */
export type CoreContent = { project_name: string, description: string, metadata: JsonValue, };
