// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alternative } from "./Alternative";

/**
 * Standalone decisions. Half-life: 180d
 */
export type DecisionContent = { decision: string, rationale: string, alternatives: Array<Alternative>, };
