// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A degradation event when a subsystem falls back to a lower-quality mode.
 */
export type DegradationEvent = { component: string, failure: string, fallback_used: string, timestamp: string, };
