// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scores for each of the 4 validation dimensions.
 */
export type DimensionScores = { 
/**
 * Citation validation: file existence, content hash drift, line validity.
 */
citation: number, 
/**
 * Temporal validation: expiry, age vs expected lifetime.
 */
temporal: number, 
/**
 * Contradiction validation: opposing memories, consensus support.
 */
contradiction: number, 
/**
 * Pattern alignment: linked patterns still exist and are consistent.
 */
pattern_alignment: number, };
