// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Projects, products, teams, systems. Half-life: 180d
 */
export type EntityContent = { entity_name: string, entity_type: string, description: string, attributes: JsonValue, };
