// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link to a file with citation information.
 */
export type FileLink = { file_path: string, line_start: number | null, line_end: number | null, 
/**
 * blake3 hash of the cited content for staleness detection.
 */
content_hash: string | null, };
