// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link to a function or method.
 */
export type FunctionLink = { function_name: string, file_path: string, signature: string | null, };
