// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of healing action to apply.
 */
export type HealingActionType = "confidence_adjust" | "citation_update" | "embedding_refresh" | "archival" | "human_review_flag";
