// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthMetrics = { total_memories: number, active_memories: number, archived_memories: number, average_confidence: number, db_size_bytes: bigint, embedding_cache_hit_rate: number, };
