// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthMetrics } from "./HealthMetrics";
import type { HealthStatus } from "./HealthStatus";
import type { SubsystemHealth } from "./SubsystemHealth";

/**
 * Comprehensive health report for all subsystems.
 */
export type HealthReport = { overall_status: HealthStatus, subsystems: Array<SubsystemHealth>, metrics: HealthMetrics, };
