// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Learned observations. Half-life: 90d
 */
export type InsightContent = { observation: string, evidence: Array<string>, };
