// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Meeting notes and action items. Half-life: 60d
 */
export type MeetingContent = { title: string, attendees: Array<string>, notes: string, action_items: Array<string>, };
