// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { NamespaceId } from "./NamespaceId";
import type { ProjectionFilter } from "./ProjectionFilter";

/**
 * A projection from one namespace to another with optional filtering.
 */
export type MemoryProjection = { 
/**
 * Unique projection identifier.
 */
id: string, 
/**
 * Source namespace to project from.
 */
source: NamespaceId, 
/**
 * Target namespace to project into.
 */
target: NamespaceId, 
/**
 * Filter criteria for which memories to include.
 */
filter: ProjectionFilter, 
/**
 * Compression level for projected memories (0–3).
 */
compression_level: number, 
/**
 * Whether this projection is live (auto-syncs on changes).
 */
live: boolean, 
/**
 * When this projection was created.
 */
created_at: string, 
/**
 * Who created this projection.
 */
created_by: AgentId, };
