// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 23 memory type variants across 3 categories.
 */
export type MemoryType = "core" | "tribal" | "procedural" | "semantic" | "episodic" | "decision" | "insight" | "reference" | "preference" | "pattern_rationale" | "constraint_override" | "decision_context" | "code_smell" | "agent_spawn" | "entity" | "goal" | "feedback" | "workflow" | "conversation" | "incident" | "meeting" | "skill" | "environment";
