// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { NamespaceId } from "./NamespaceId";
import type { NamespacePermission } from "./NamespacePermission";

/**
 * Access control list for a namespace.
 */
export type NamespaceACL = { 
/**
 * The namespace this ACL applies to.
 */
namespace: NamespaceId, 
/**
 * Permission grants: (agent_id, permissions).
 */
grants: Array<[AgentId, Array<NamespacePermission>]>, };
