// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamespaceScope } from "./NamespaceScope";

/**
 * A namespace identifier composed of a scope and a name.
 *
 * URI format: `{scope}://{name}/`
 * - `agent://default/` — the default single-agent namespace
 * - `team://backend/` — a team-scoped namespace
 * - `project://cortex/` — a project-scoped namespace
 */
export type NamespaceId = { 
/**
 * The scope determines visibility and default permissions.
 */
scope: NamespaceScope, 
/**
 * Human-readable namespace name.
 */
name: string, };
