// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Link to a code pattern.
 */
export type PatternLink = { pattern_id: string, pattern_name: string, };
