// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProceduralStep } from "./ProceduralStep";

/**
 * How-to procedures. Half-life: 180d
 */
export type ProceduralContent = { title: string, steps: Array<ProceduralStep>, prerequisites: Array<string>, };
