// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProvenanceHop } from "./ProvenanceHop";
import type { ProvenanceOrigin } from "./ProvenanceOrigin";

/**
 * Full provenance record for a memory, including origin and chain of custody.
 */
export type ProvenanceRecord = { 
/**
 * The memory this provenance record belongs to.
 */
memory_id: string, 
/**
 * How this memory was originally created.
 */
origin: ProvenanceOrigin, 
/**
 * Chain of custody hops (ordered, oldest first).
 */
chain: Array<ProvenanceHop>, 
/**
 * Cumulative confidence through the chain (product of hop deltas).
 */
chain_confidence: number, };
