// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ProvenanceAction } from "./ProvenanceAction";

/**
 * A single hop in the provenance chain.
 */
export type ProvenanceHop = { 
/**
 * The agent that performed this action.
 */
agent_id: AgentId, 
/**
 * What action was taken.
 */
action: ProvenanceAction, 
/**
 * When this hop occurred.
 */
timestamp: string, 
/**
 * Change in confidence at this hop (range: -1.0 to 1.0).
 */
confidence_delta: number, };
