// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrossAgentRelation } from "./CrossAgentRelation";
import type { RelationshipType } from "./RelationshipType";

/**
 * An edge in the relationship graph between two memories.
 */
export type RelationshipEdge = { source_id: string, target_id: string, relationship_type: RelationshipType, 
/**
 * Strength of the relationship, 0.0–1.0.
 */
strength: number, 
/**
 * Evidence supporting this relationship.
 */
evidence: Array<string>, 
/**
 * Cross-agent relation detail (only set when relationship_type == CrossAgent).
 */
cross_agent_relation?: CrossAgentRelation | null, };
