// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Consolidated knowledge from episodic memories. Half-life: 90d
 */
export type SemanticContent = { knowledge: string, source_episodes: Array<string>, consolidation_confidence: number, };
