// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accumulated evidence for trust computation.
 *
 * Trust formula: `(validated + useful) / (total + 1) * (1 - contradicted / (total + 1))`
 */
export type TrustEvidence = { 
/**
 * Number of memories validated as correct.
 */
validated_count: bigint, 
/**
 * Number of memories that contradicted known facts.
 */
contradicted_count: bigint, 
/**
 * Number of memories that were useful in decisions.
 */
useful_count: bigint, 
/**
 * Total memories received from the target agent.
 */
total_received: bigint, };
