// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionScores } from "./DimensionScores";
import type { HealingAction } from "./HealingAction";

/**
 * Result of 4-dimension memory validation.
 */
export type ValidationResult = { memory_id: string, 
/**
 * Score per dimension (0.0–1.0).
 */
dimension_scores: DimensionScores, 
/**
 * Overall validation score.
 */
overall_score: number, 
/**
 * Healing actions to apply.
 */
healing_actions: Array<HealingAction>, 
/**
 * Whether the memory passed validation.
 */
passed: boolean, };
