// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStep } from "./WorkflowStep";

/**
 * Step-by-step processes. Half-life: 180d
 */
export type WorkflowContent = { name: string, steps: Array<WorkflowStep>, trigger: string | null, };
