mod audit_entry;
mod causal_narrative;
mod compressed_memory;
mod consolidation_metrics;
mod consolidation_result;
mod contradiction;
mod degradation_event;
mod embedding_info;
mod generation_context;
mod health_report;
mod learning_result;
mod prediction_result;
mod retrieval_context;
mod session_context;
mod validation_result;
mod why_context;

pub use audit_entry::{AuditActor, AuditEntry, AuditOperation};
pub use causal_narrative::{CausalNarrative, NarrativeSection};
pub use compressed_memory::CompressedMemory;
pub use consolidation_metrics::ConsolidationMetrics;
pub use consolidation_result::ConsolidationResult;
pub use contradiction::{Contradiction, ContradictionType, DetectionStrategy};
pub use degradation_event::DegradationEvent;
pub use embedding_info::{EmbeddingModelInfo, EmbeddingModelStatus};
pub use generation_context::{BudgetAllocation, GenerationContext};
pub use health_report::{HealthMetrics, HealthReport, HealthStatus, SubsystemHealth};
pub use learning_result::LearningResult;
pub use prediction_result::PredictionResult;
pub use retrieval_context::RetrievalContext;
pub use session_context::SessionContext;
pub use validation_result::{DimensionScores, HealingAction, HealingActionType, ValidationResult};
pub use why_context::{WhyContext, WhyEntry};
